version: "3.8"
services:
  gs:
    image: ubuntu:24.04
    network_mode: host
    ports:
      - ${PORT}:${PORT}/udp
    volumes:
      - ./bin:/opt/bim/bin:ro
      - ./etc:/opt/bim/etc:ro
      - ./log:/opt/bim/log
      - ./contest:/opt/bim/contest/
    deploy:
      restart_policy:
        condition: on-failure
    command: >
        bash -c "cp /opt/bim/etc/logrotate.d/* /etc/logrotate.d/
        && /opt/bim/bin/bim-server
        --contest-timeline-folder /opt/bim/contest/
        --log-file /opt/bim/log/bim-server.txt
        --port ${PORT}
        > /opt/bim/log/bim-server.stdout.txt
        2> /opt/bim/log/bim-server.stderr.txt"
