---
name: Android

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: >
    ${{github.workflow }}
    -${{ github.event.pull_request.number || github.ref}}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:23.10"

    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - uses: actions/checkout@v3

      - name: Set strings
        id: strings
        run: |
          echo "target_platform=android" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: >
          ./ci/install-minimal-environment.sh
          --compiler g++
          --target-platform ${{steps.strings.outputs.target_platform}}
          ;

      - if: ${{matrix.build_type == 'debug'}}
        name: Initialize debug keystore
        run: >
          ./ci/initialize-android-keystore.sh
          --build-type ${{matrix.build_type}}
          --output-dir ./android/app/
          ;

      - if: ${{matrix.build_type == 'release'}}
        name: Initialize release keystore
        env:
          BIM_KEYSTORE_PASSWORD: ${{secrets.BIM_KEYSTORE_PASSWORD}}
          BIM_RELEASE_KEYSTORE: ${{secrets.BIM_RELEASE_KEYSTORE}}
        run: >
          ./ci/initialize-android-keystore.sh
          --build-type ${{matrix.build_type}}
          --output-dir ./android/app/
          ;

      - name: Launch build
        run: >
          ./setup.sh
          --target-platform ${{steps.strings.outputs.target_platform}}
          --build-type ${{matrix.build_type}}
