---
name: Configure, build, test.

on:
  push:
  pull_request:

concurrency:
  group: >
    ${{github.workflow }}
    -${{ github.event.pull_request.number || github.ref}}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    strategy:
      matrix:
        # Last LTS and last non-LTS.
        container: ["ubuntu:23.10", "ubuntu:24.04"]
        build_type: [release, debug]
        compiler: [g++, clang-17, clang-18]
        maybe_incremental: [--incremental, ""]
        exclude:
          - container: "ubuntu:23.10"
            compiler: clang-18
          - container: "ubuntu:24.04"
            compiler: clang-17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set strings
        id: strings
        run: |
          echo "target_platform=linux" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: >
          ./ci/install-minimal-environment.sh
          --compiler ${{matrix.compiler}}
          --target-platform ${{steps.strings.outputs.target_platform}}
          ;

      - name: Launch build
        run: >
          ./setup.sh
          --target-platform ${{steps.strings.outputs.target_platform}}
          --build-type ${{matrix.build_type}} ${{matrix.maybe_incremental}}

      - name: Archive artifacts
        if: |
          (matrix.maybe_incremental == '')
          && (matrix.container == 'ubuntu:24.04')
        uses: actions/upload-artifact@v4
        with:
          name: server-${{matrix.build_type}}-${{matrix.compiler}}
          path: build/linux/*/apps/server/bim-server
