---
name: Repository health

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: >
    ${{github.workflow }}
    -${{ github.event.pull_request.number || github.ref}}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:23.10"

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          apt-get update ;
          apt-get install --yes clang-format shellcheck yamllint ;

      - name: Check repository state
        run: ./ci/repository-health.sh
