---
name: Sanitizers

on:
  push:
  pull_request:

concurrency:
  group: >
    ${{github.workflow }}
    -${{ github.event.pull_request.number || github.ref}}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:23.10"

    strategy:
      matrix:
        build_type: [asan, tsan]

    steps:
      - uses: actions/checkout@v3

      - name: Set strings
        id: strings
        run: |
          echo "target_platform=linux" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: >
          ./ci/install-minimal-environment.sh
          --compiler g++
          --target-platform ${{steps.strings.outputs.target_platform}}
          ;

      - name: Launch build
        run: >
          ./setup.sh
          --target-platform ${{steps.strings.outputs.target_platform}}
          --build-type ${{matrix.build_type}}
